Add Jadu detection
HTTPArchive/wappalyzer pull request #84
Opened 2024-12-06 12:52 UTC by jamesjacobs

Add Jadu platform detection.

---

**Test websites**:

- https://www.jadu.net/
- https://www.wasatchcounty.gov/
- https://www.runnymede.gov.uk/
- https://www.rochdale.gov.uk/
- https://www.nuneatonandbedworth.gov.uk/
- https://chorley.gov.uk/
- https://www.ribblevalley.gov.uk/
- https://www.hial.co.uk/
- https://www.slough.gov.uk/
- https://www.oxford.gov.uk/ 
- https://www.dartford.gov.uk/

2024-12-09 19:02 UTC, max-ostapenko commented on src/technologies/j.json
> +    "dom": "footer a[href*='jadu.net']",
```suggestion
```
Could we skip this?
It can give false positive results if technology is mentioned but not actually present.

2024-12-09 19:23 UTC, max-ostapenko commented on src/technologies/j.json
> +    "dom": "footer a[href*='jadu.net']",
```suggestion
    "headers": {"node": "^jadu-web-."},
```

This tech returns quite a unique header, so I would probably rely on this one.

2024-12-09 19:25 UTC, max-ostapenko requested changes

2024-12-09 19:25 UTC, max-ostapenko commented on src/technologies/j.json
> +      "/widgets/js/widget\\.js"
These are quite common paths that are available on a number of origins.
```suggestion
      "/site/js/almond\\.min\\.js",
```

Example: https://www.napleshomes.properties/, https://www.barendonk.nl/

2024-12-09 19:25 UTC, max-ostapenko commented on src/technologies/j.json
> +      "/widgets/js/widget\\.js"
If `almond.min.js` duplicates the header, let's keep the header only to get the best results.

2024-12-12 10:58 UTC, jamesjacobs commented
@max-ostapenko thanks for the feedback. I've removed the `scriptSrc` and link check. I've added the header check, though that header is not present on all Jadu sites, so as a fallback I've added a check for some text which is generally present in the footer on Jadu powered websites.

2024-12-12 11:07 UTC, max-ostapenko approved these changes

2024-12-20 13:00 UTC, merged